---
abstract: 'Moose role that adds serialization support to any class'
author:
  - 'Robin Smidsrød <robin@smidsrod.no>'
build_requires:
  Data::Serializer::JSON: 0
  English: 0
  JSON: 0
  Moose: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Serializable
requires:
  Carp: 0
  Class::MOP: 0
  Moose::Role: 0
  Storable: 0
  perl: 5.006
resources:
  repository: git://github.com/robinsmidsrod/Data-Serializable.git
version: 0.40.0
